DROP TABLE IF EXISTS `accounts`;
CREATE TABLE IF NOT EXISTS `accounts` (
	`id` INT(11) unsigned NOT NULL AUTO_INCREMENT,
	`surname` VARCHAR(100) NULL DEFAULT NULL DEFAULT '',
	`name` VARCHAR(100) NULL DEFAULT NULL DEFAULT '',
	`patronymic` VARCHAR(100) NULL DEFAULT NULL DEFAULT '',
	`account` VARCHAR(50) NULL DEFAULT NULL DEFAULT '',
	`mail` VARCHAR(50) NULL DEFAULT NULL DEFAULT '',
	PRIMARY KEY (`id`)
)
ENGINE=InnoDB  
DEFAULT CHARSET=utf8
AUTO_INCREMENT=1
;
