DROP TABLE IF EXISTS `accounts`;
CREATE TABLE IF NOT EXISTS `accounts` (
	`id` INT(11) unsigned NOT NULL AUTO_INCREMENT,
	`surname` VARCHAR(100) NULL DEFAULT NULL DEFAULT '',
	`name` VARCHAR(100) NULL DEFAULT NULL DEFAULT '',
	`patronymic` VARCHAR(100) NULL DEFAULT NULL DEFAULT '',
	`account` VARCHAR(50) NULL DEFAULT NULL DEFAULT '',
	`mail` VARCHAR(50) NULL DEFAULT NULL DEFAULT '',
	`phone` VARCHAR(20) NULL DEFAULT NULL DEFAULT '',

	`sp1` VARCHAR(10) NULL DEFAULT NULL DEFAULT '',
	`sp2` VARCHAR(10) NULL DEFAULT NULL DEFAULT '',
	`sp3` VARCHAR(10) NULL DEFAULT NULL DEFAULT '',

	`tab` VARCHAR(10) NULL DEFAULT NULL DEFAULT '',
	`position` VARCHAR(200) NULL DEFAULT NULL DEFAULT '',
	PRIMARY KEY (`id`)
)
ENGINE=InnoDB  
DEFAULT CHARSET=utf8
AUTO_INCREMENT=1
;
