DROP TABLE IF EXISTS `computers`;
CREATE TABLE IF NOT EXISTS `computers` (
	`id` INT(11) unsigned NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NULL DEFAULT NULL DEFAULT '',
	`ip` VARCHAR(100) NULL DEFAULT NULL DEFAULT '',
	`system` VARCHAR(50) NULL DEFAULT NULL DEFAULT '',
	`arch` VARCHAR(10) NULL DEFAULT NULL DEFAULT '',
	PRIMARY KEY (`id`)
)
ENGINE=InnoDB  
DEFAULT CHARSET=utf8
AUTO_INCREMENT=1
;
