DROP TABLE IF EXISTS `logs`;
CREATE TABLE IF NOT EXISTS `logs` (
	`id` INT(11) unsigned NOT NULL AUTO_INCREMENT,
	`dt` DATE NULL DEFAULT NULL,
	`tm` TIME NULL DEFAULT NULL,
	`computer` VARCHAR(50) NULL DEFAULT NULL DEFAULT '',
	`account` VARCHAR(50) NULL DEFAULT NULL DEFAULT '',
	`domain` VARCHAR(50) NULL DEFAULT NULL DEFAULT '',
	`action` ENUM('logon','logoff') NOT NULL DEFAULT 'logon',
	PRIMARY KEY (`id`)
)
ENGINE=InnoDB  
DEFAULT CHARSET=utf8
AUTO_INCREMENT=1
;
