DROP TABLE IF EXISTS `notes`;
CREATE TABLE IF NOT EXISTS `notes` (
	`id` INT(11) unsigned NOT NULL AUTO_INCREMENT,
	`alias` VARCHAR(50) NULL DEFAULT NULL DEFAULT '',
	`note` TEXT NULL DEFAULT NULL DEFAULT '',
	PRIMARY KEY (`id`)
)
ENGINE=InnoDB  
DEFAULT CHARSET=utf8
AUTO_INCREMENT=1
;
