DROP TABLE IF EXISTS `sp`;
CREATE TABLE IF NOT EXISTS `sp` (
	`id` INT(11) unsigned NOT NULL AUTO_INCREMENT,
	`code` VARCHAR(20) NULL DEFAULT NULL DEFAULT '',
	`name` VARCHAR(200) NULL DEFAULT NULL DEFAULT '',
	`level` INT(11) NULL DEFAULT NULL DEFAULT 1,
	PRIMARY KEY (`id`)
)
ENGINE=InnoDB  
DEFAULT CHARSET=utf8
AUTO_INCREMENT=1
;
